apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo
  labels:
    app: react-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-demo
  template:
    metadata:
      labels:
        app: react-demo
    spec:
      containers:
        - name: react-demo
          image: 316770681739.dkr.ecr.ap-south-1.amazonaws.com/react-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

