apiVersion: v1
kind: Service
metadata:
  name: react-demo-service
  labels:
    app: react-demo
spec:
  type: LoadBalancer
  selector:
    app: react-demo
  ports:
    - port: 80
      targetPort: 80
